@echo off
echo Starting Diamond Price Predictor...
echo Installing dependencies...
"f:/Machine Learning/DiamondPricePredictor/.venv/Scripts/pip.exe" install -r requirements.txt
echo.
echo Launching Streamlit app...
"f:/Machine Learning/DiamondPricePredictor/.venv/Scripts/streamlit.exe" run app.py
pause
